name: ordinal_formatter_example
description: Demonstrates how to use the ordinal_formatter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ordinal_formatter:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true